export const MAJOR_ARCANA_CARDS = [
  { cardName: "The Fool", value: "fool" },
  { cardName: "The Magician", value: "magician" },
  { cardName: "The High Priestess", value: "high-priestess" },
  { cardName: "The Empress", value: "empress" },
  { cardName: "The Emperor", value: "emperor" },
  { cardName: "The Hierophant", value: "hierophant" },
  { cardName: "The Lovers", value: "lovers" },
  { cardName: "The Chariot", value: "chariot" },
  { cardName: "Strength", value: "strength" },
  { cardName: "The Hermit", value: "hermit" },
  { cardName: "Wheel of Fortune", value: "wheel-of-fortune" },
  { cardName: "Justice", value: "justice" },
  { cardName: "The Hanged Man", value: "hanged-man" },
  { cardName: "Death", value: "death" },
  { cardName: "Temperance", value: "temperance" },
  { cardName: "The Devil", value: "devil" },
  { cardName: "The Tower", value: "tower" },
  { cardName: "The Star", value: "star" },
  { cardName: "The Moon", value: "moon" },
  { cardName: "The Sun", value: "sun" },
  { cardName: "Judgement", value: "judgement" },
  { cardName: "The World", value: "world" },
];

export const MINOR_ARCANA_CARDS = [
  // Swords
  { cardName: "Ace of Swords", value: "ace-of-swords" },
  { cardName: "Two of Swords", value: "two-of-swords" },
  { cardName: "Three of Swords", value: "three-of-swords" },
  { cardName: "Four of Swords", value: "four-of-swords" },
  { cardName: "Five of Swords", value: "five-of-swords" },
  { cardName: "Six of Swords", value: "six-of-swords" },
  { cardName: "Seven of Swords", value: "seven-of-swords" },
  { cardName: "Eight of Swords", value: "eight-of-swords" },
  { cardName: "Nine of Swords", value: "nine-of-swords" },
  { cardName: "Ten of Swords", value: "ten-of-swords" },
  { cardName: "Page of Swords", value: "page-of-swords" },
  { cardName: "Knight of Swords", value: "knight-of-swords" },
  { cardName: "Queen of Swords", value: "queen-of-swords" },
  { cardName: "King of Swords", value: "king-of-swords" },

  // Cups
  { cardName: "Ace of Cups", value: "ace-of-cups" },
  { cardName: "Two of Cups", value: "two-of-cups" },
  { cardName: "Three of Cups", value: "three-of-cups" },
  { cardName: "Four of Cups", value: "four-of-cups" },
  { cardName: "Five of Cups", value: "five-of-cups" },
  { cardName: "Six of Cups", value: "six-of-cups" },
  { cardName: "Seven of Cups", value: "seven-of-cups" },
  { cardName: "Eight of Cups", value: "eight-of-cups" },
  { cardName: "Nine of Cups", value: "nine-of-cups" },
  { cardName: "Ten of Cups", value: "ten-of-cups" },
  { cardName: "Page of Cups", value: "page-of-cups" },
  { cardName: "Knight of Cups", value: "knight-of-cups" },
  { cardName: "Queen of Cups", value: "queen-of-cups" },
  { cardName: "King of Cups", value: "king-of-cups" },

  // Wands
  { cardName: "Ace of Wands", value: "ace-of-wands" },
  { cardName: "Two of Wands", value: "two-of-wands" },
  { cardName: "Three of Wands", value: "three-of-wands" },
  { cardName: "Four of Wands", value: "four-of-wands" },
  { cardName: "Five of Wands", value: "five-of-wands" },
  { cardName: "Six of Wands", value: "six-of-wands" },
  { cardName: "Seven of Wands", value: "seven-of-wands" },
  { cardName: "Eight of Wands", value: "eight-of-wands" },
  { cardName: "Nine of Wands", value: "nine-of-wands" },
  { cardName: "Ten of Wands", value: "ten-of-wands" },
  { cardName: "Page of Wands", value: "page-of-wands" },
  { cardName: "Knight of Wands", value: "knight-of-wands" },
  { cardName: "Queen of Wands", value: "queen-of-wands" },
  { cardName: "King of Wands", value: "king-of-wands" },

  // Pentacles
  { cardName: "Ace of Pentacles", value: "ace-of-pentacles" },
  { cardName: "Two of Pentacles", value: "two-of-pentacles" },
  { cardName: "Three of Pentacles", value: "three-of-pentacles" },
  { cardName: "Four of Pentacles", value: "four-of-pentacles" },
  { cardName: "Five of Pentacles", value: "five-of-pentacles" },
  { cardName: "Six of Pentacles", value: "six-of-pentacles" },
  { cardName: "Seven of Pentacles", value: "seven-of-pentacles" },
  { cardName: "Eight of Pentacles", value: "eight-of-pentacles" },
  { cardName: "Nine of Pentacles", value: "nine-of-pentacles" },
  { cardName: "Ten of Pentacles", value: "ten-of-pentacles" },
  { cardName: "Page of Pentacles", value: "page-of-pentacles" },
  { cardName: "Knight of Pentacles", value: "knight-of-pentacles" },
  { cardName: "Queen of Pentacles", value: "queen-of-pentacles" },
  { cardName: "King of Pentacles", value: "king-of-pentacles" },
];
